<a href="https://colab.research.google.com/github/emagif/PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [140]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

#### Creating Tensors

#### Pytorch tensors are created using torch.Tensor()

# Scalar

In [141]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [142]:
scalar.ndim

0

In [143]:
scalar.item()

7

In [144]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [145]:
vector.ndim

1

In [146]:
vector.shape

torch.Size([2])

# Matrix

In [147]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [148]:
MATRIX.ndim

2

In [149]:
MATRIX.shape

torch.Size([2, 2])

In [150]:
MATRIX[0]

tensor([7, 8])

In [151]:
MATRIX[1]

tensor([ 9, 10])

# Tensor


In [152]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 7], [2, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 1, 5]]])

In [153]:
TENSOR.ndim

3

In [154]:
TENSOR.shape

torch.Size([1, 3, 3])

In [155]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 1, 5]])

In [156]:
tensor1 = torch.tensor([[[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [9, 0, 2, 3, 4]]])
tensor1

tensor([[[1, 2, 3, 4, 5],
         [4, 5, 6, 7, 8],
         [9, 0, 2, 3, 4]]])

In [157]:
tensor1.shape

torch.Size([1, 3, 5])

In [158]:
tensor1.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full or random numbers and thej adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update'

In [159]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3871, 0.5899, 0.7586, 0.8985],
        [0.2050, 0.5738, 0.0904, 0.5200],
        [0.7468, 0.4426, 0.1697, 0.9218]])

In [160]:
random_tensor.ndim

2

In [161]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor

tensor([[[0.3388, 0.5876, 0.3329],
         [0.3110, 0.0235, 0.8018],
         [0.1537, 0.1483, 0.1018],
         ...,
         [0.8680, 0.7036, 0.5113],
         [0.2399, 0.2527, 0.4056],
         [0.0626, 0.9703, 0.2727]],

        [[0.4690, 0.8361, 0.0478],
         [0.6185, 0.3779, 0.1166],
         [0.9295, 0.8519, 0.3159],
         ...,
         [0.2912, 0.5264, 0.9863],
         [0.5488, 0.0274, 0.2821],
         [0.3461, 0.9151, 0.1164]],

        [[0.9035, 0.6466, 0.7122],
         [0.1869, 0.4999, 0.1309],
         [0.2044, 0.1936, 0.8493],
         ...,
         [0.9197, 0.7936, 0.0728],
         [0.4106, 0.0133, 0.1666],
         [0.5282, 0.6652, 0.4413]],

        ...,

        [[0.5445, 0.8302, 0.0791],
         [0.7733, 0.2020, 0.3452],
         [0.5524, 0.6354, 0.9066],
         ...,
         [0.0915, 0.5450, 0.9427],
         [0.6118, 0.9563, 0.2631],
         [0.0130, 0.8304, 0.7359]],

        [[0.5938, 0.3856, 0.8792],
         [0.0225, 0.6676, 0.4762],
         [0.

In [162]:
random_image_tensor.ndim

3

In [163]:
random_image_tensor.shape


torch.Size([224, 224, 3])

## Zeros and ones

In [164]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [165]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [166]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [167]:
ones.dtype

torch.float32

In [168]:
random_tensor.dtype

torch.float32

# Create a range od tensor and tensors-like

In [169]:
one_to_ten = torch.arange(0, 10)

## Creating tensors-like

In [170]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [171]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

## Tensor atributes

In [172]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [173]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor,can use 'tensor.dtype'
2. Tensors not right shape - to get shape from tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'


In [174]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1029, 0.6175, 0.9843, 0.6527],
        [0.4230, 0.2437, 0.0745, 0.1607],
        [0.9972, 0.9622, 0.3539, 0.6053]])

In [175]:
print(f"Shape of tensor: {some_tensor.shape}")

Shape of tensor: torch.Size([3, 4])


In [176]:
print(f"Datatype of tensor: {some_tensor.dtype}")

Datatype of tensor: torch.float32


In [177]:
print(f"Device tensor is on: {some_tensor.device}")

Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

### Tensor operations include:

 Tensor operations include:
 * Addition
 * Substraction
 * Multiplication
 * Division
 * Matrix multiplication

In [178]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [179]:
# Multiply tensor
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [180]:
# Substract 10
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [181]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([110, 120, 130])

### Matrix multiplication

Two main ways of performing multiplication in NN and DL

1. Element-wise multiplication
2. Matix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* the amount of columns of the first matrix must be the same as the amount of rows in the second matrix
2. The result of the multiplication will be a matrix of dimensions combined of the amount of the rows of the first matrix and the amount of columns of the second matrix.

In [182]:
# Element-wise multiplication
print(tensor*tensor)


tensor([10000, 12100, 14400])


In [183]:
torch.matmul(tensor, tensor)

tensor(36500)

In [184]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 +  3 * 3

14

In [185]:
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(36500)


### One of the most common errors in deep learning: shape errors

In [186]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])


# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it is an alias)


To fix our tensor shape issues we can manipulate the shape of one of our tensor using Transpose

tensor_B.T



In [187]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [188]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [189]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc. (tensor aggregation)

In [190]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [191]:
# Find the min
torch.min(x)
x.min()

tensor(0)

In [192]:
# Find the average
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [193]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [194]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

## Finding the positional min and max

In [195]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [196]:
x[0]

tensor(0)

In [197]:
# Find the position in tensor that has the maximum value with argmax(
x.argmax()

tensor(9)

In [198]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with a dimensions permuted (swapped) in a certain way

In [200]:
# Creating a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [202]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
3h 05min