<a href="https://colab.research.google.com/github/emagif/PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [104]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

#### Creating Tensors

#### Pytorch tensors are created using torch.Tensor()

# Scalar

In [105]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [106]:
scalar.ndim

0

In [107]:
scalar.item()

7

In [108]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [109]:
vector.ndim

1

In [110]:
vector.shape

torch.Size([2])

# Matrix

In [111]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [112]:
MATRIX.ndim

2

In [113]:
MATRIX.shape

torch.Size([2, 2])

In [114]:
MATRIX[0]

tensor([7, 8])

In [115]:
MATRIX[1]

tensor([ 9, 10])

# Tensor


In [116]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 7], [2, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 1, 5]]])

In [117]:
TENSOR.ndim

3

In [118]:
TENSOR.shape

torch.Size([1, 3, 3])

In [119]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 1, 5]])

In [120]:
tensor1 = torch.tensor([[[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [9, 0, 2, 3, 4]]])
tensor1

tensor([[[1, 2, 3, 4, 5],
         [4, 5, 6, 7, 8],
         [9, 0, 2, 3, 4]]])

In [121]:
tensor1.shape

torch.Size([1, 3, 5])

In [122]:
tensor1.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full or random numbers and thej adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update'

In [123]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1568, 0.2083, 0.3289, 0.1054],
        [0.9192, 0.4008, 0.9302, 0.6558],
        [0.0766, 0.8460, 0.3624, 0.3083]])

In [124]:
random_tensor.ndim

2

In [125]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor

tensor([[[0.0850, 0.0029, 0.6431],
         [0.3908, 0.6947, 0.0897],
         [0.8712, 0.1330, 0.4137],
         ...,
         [0.9885, 0.3997, 0.6986],
         [0.0535, 0.7878, 0.3446],
         [0.1197, 0.5731, 0.7422]],

        [[0.9327, 0.1946, 0.2539],
         [0.5961, 0.6356, 0.6922],
         [0.7744, 0.3866, 0.7778],
         ...,
         [0.6065, 0.4659, 0.8434],
         [0.0495, 0.6988, 0.4185],
         [0.7283, 0.4978, 0.3149]],

        [[0.4460, 0.7700, 0.1527],
         [0.1840, 0.3880, 0.3186],
         [0.6964, 0.8365, 0.4465],
         ...,
         [0.8118, 0.7759, 0.9800],
         [0.5757, 0.0468, 0.8569],
         [0.5458, 0.5099, 0.0237]],

        ...,

        [[0.5960, 0.2374, 0.3593],
         [0.6072, 0.5017, 0.2613],
         [0.5219, 0.0627, 0.3844],
         ...,
         [0.2566, 0.9360, 0.5737],
         [0.2536, 0.1119, 0.4822],
         [0.2090, 0.6940, 0.2454]],

        [[0.8140, 0.9271, 0.2446],
         [0.3553, 0.9089, 0.9329],
         [0.

In [126]:
random_image_tensor.ndim

3

In [127]:
random_image_tensor.shape


torch.Size([224, 224, 3])

## Zeros and ones

In [128]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [129]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [130]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [131]:
ones.dtype

torch.float32

In [132]:
random_tensor.dtype

torch.float32

# Create a range od tensor and tensors-like

In [133]:
one_to_ten = torch.arange(0, 10)

## Creating tensors-like

In [134]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [135]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

## Tensor atributes

In [136]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [137]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor,can use 'tensor.dtype'
2. Tensors not right shape - to get shape from tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'


In [138]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1167, 0.3571, 0.5386, 0.2662],
        [0.1353, 0.1664, 0.5620, 0.3337],
        [0.3034, 0.6037, 0.1452, 0.8953]])

In [139]:
print(f"Shape of tensor: {some_tensor.shape}")

Shape of tensor: torch.Size([3, 4])


In [140]:
print(f"Datatype of tensor: {some_tensor.dtype}")

Datatype of tensor: torch.float32


In [141]:
print(f"Device tensor is on: {some_tensor.device}")

Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

### Tensor operations include:

 Tensor operations include:
 * Addition
 * Substraction
 * Multiplication
 * Division
 * Matrix multiplication

In [142]:
# Create a tensor and add 10
tensor = torch.tensor([1, 2, 3])
tensor = tensor + 10
tensor

tensor([11, 12, 13])

In [143]:
# Multiply tensor
tensor = tensor * 10
tensor

tensor([110, 120, 130])

In [144]:
# Substract 10
tensor = tensor - 10
tensor

tensor([100, 110, 120])

In [145]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)
torch.add(tensor, 10)

tensor([110, 120, 130])

### Matrix multiplication

Two main ways of performing multiplication in NN and DL

1. Element-wise multiplication
2. Matix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* the amount of columns of the first matrix must be the same as the amount of rows in the second matrix
2. The result of the multiplication will be a matrix of dimensions combined of the amount of the rows of the first matrix and the amount of columns of the second matrix.

In [146]:
# Element-wise multiplication
print(tensor*tensor)


tensor([10000, 12100, 14400])


In [147]:
torch.matmul(tensor, tensor)

tensor(36500)

In [148]:
# Matrix multiplication by hand
1 * 1 + 2 * 2 +  3 * 3

14

In [149]:
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(36500)


### One of the most common errors in deep learning: shape errors

In [150]:
# Shapes for matrix multiplication

tensor_A = torch.tensor([[1, 2], [3, 4], [5, 6]])

tensor_B = torch.tensor([[7, 10], [8, 11], [9, 12]])


# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it is an alias)


To fix our tensor shape issues we can manipulate the shape of one of our tensor using Transpose

tensor_B.T



In [151]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [152]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [153]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc. (tensor aggregation)

In [154]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [155]:
# Find the min
torch.min(x)
x.min()

tensor(0)

In [156]:
# Find the average
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [157]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [158]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

## Finding the positional min and max

In [159]:
# Find the position in tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [160]:
x[0]

tensor(0)

In [161]:
# Find the position in tensor that has the maximum value with argmax(
x.argmax()

tensor(9)

In [162]:
x[9]

tensor(90)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with a dimensions permuted (swapped) in a certain way

In [163]:
# Creating a tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [164]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [165]:
# Change the view
z = x.view(1, 9)
z, z.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [166]:
# Changing z changes x (because a view a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [167]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [168]:
v_stacked = torch.vstack([x, x, x, x])
v_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [169]:
h_stacked = torch.hstack([x, x, x, x])
h_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [170]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [171]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [172]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # height, width, color_channels

# Permute the original tensor to rearrange the axis (or dimensions) order
x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")



Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [173]:
x_permuted_again = x_original.permute(1, 2, 0)
x_permuted_again.shape

torch.Size([224, 3, 224])

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy


In [174]:
# Create a tensor
x = torch.arange(1,10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [175]:
# Let's index on our new tensors
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [176]:
 # Let's index on the middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [177]:
# Let's index on the most inner bracket (last dimension)
x[0, 0, 0]

tensor(1)

In [178]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [179]:
# Get all values of 0th and 1st dimensions but inly index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [180]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [181]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [182]:
# Index to return '9'
x[0][2][2]

tensor(9)

In [183]:
# Index to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

Because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyToch tensor -> NumPy -> `torch.Tensor.numpy()`

In [184]:
# NumPy array to tensor

import numpy as np

array = np.arange(1, 8)
print(f"Numpy array: {array}")
tensor = torch.from_numpy(array) # when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float 64 unless specified otherwise
print(f"PyTorch tensor: {tensor}")

Numpy array: [1 2 3 4 5 6 7]
PyTorch tensor: tensor([1, 2, 3, 4, 5, 6, 7])


In [185]:
# Change the value of array, what will this do to tensor?
array = array + 1
array, tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [186]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [187]:
numpy_tensor.dtype

dtype('float32')

In [188]:
# Change the tensor, what happens to numpy_tensor?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:
 `start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

 To reduce the randomness in NN and PyTorch comes the concept of a **random seed**.

 Essentially what the random seed does is "flavour" the randomness.

In [189]:
# Create two random tensors

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)

print(random_tensor_A == random_tensor_B)

tensor([[0.7169, 0.7576, 0.3273, 0.7462],
        [0.7254, 0.8974, 0.2768, 0.6498],
        [0.0583, 0.2528, 0.8281, 0.0411]])
tensor([[0.1029, 0.0332, 0.7918, 0.4645],
        [0.1734, 0.8508, 0.0282, 0.6474],
        [0.3719, 0.1917, 0.5551, 0.1097]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [190]:
# Let's make some random but reproducable tensors
# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything good.

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there is lots of options...
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2 and 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch documentation.




In [191]:
!nvidia-smi

Tue Apr  2 14:55:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P0              33W /  70W |    105MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [192]:
# Check for GPU access with PyTorch
torch.cuda.is_available()

True

For PyTorch since is it possible of running compute on the GPU or CPU, it is best practice to setup device agnostic code (refer to the documentation)

E.g. run on GPU if available, else default to CPU

In [193]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [194]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [195]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor ot on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [196]:
# Move tensor to GPU (if available)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [197]:
# If tensor is on GPu, cannot transform it to NumPy
# To fiz the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

### Exercises & Extra-curriculum

#### Create a random tensor with shape (7, 7)

In [198]:
random_tensor = torch.rand(7, 7)
random_tensor, random_tensor.shape

(tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666],
         [0.6274, 0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753, 0.8860],
         [0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423],
         [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886],
         [0.5895, 0.7539, 0.1952, 0.0050, 0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315]]),
 torch.Size([7, 7]))

#### Perform a matrix multiplication on the tensor above and another tensor with shape (1, 7)

In [199]:
second_tensor = torch.rand(1, 7)
transposed_second_tensor = second_tensor.T
transposed_second_tensor

tensor([[0.1587],
        [0.6542],
        [0.3278],
        [0.6532],
        [0.3958],
        [0.9147],
        [0.2036]])

In [200]:
# Multiplication
result = random_tensor.matmul(transposed_second_tensor)
result, result.shape

(tensor([[1.9625],
         [1.0950],
         [0.9967],
         [1.8910],
         [1.9205],
         [1.0674],
         [1.6949]]),
 torch.Size([7, 1]))

#### Set the random seed to `0` and do previous steps over again

In [202]:
torch.manual_seed(0)
tensor_1 = torch.rand(7, 7)
torch.manual_seed(0)
tensor_2 = torch.rand(1, 7)
print(tensor_1, tensor_2)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]) tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


In [203]:
transposed_second_tensor = tensor_2.T
transposed_second_tensor

tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

In [204]:
multiplying_result = tensor_1.matmul(transposed_second_tensor)
multiplying_result

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

In [209]:
torch.cuda.manual_seed(1234)
first_random_tensor = torch.rand(2, 3)
second_random_tensor = torch.rand(2, 3)
transposed_random_tensor = second_random_tensor.T
first_random_tensor_on_gpu = first_random_tensor.to(device)
second_random_tensor_on_gpu = transposed_random_tensor.to(device)
result_of_multiplying = first_random_tensor_on_gpu.matmul(second_random_tensor_on_gpu)
result_of_multiplying

tensor([[0.8386, 0.5860],
        [1.0676, 0.5279]], device='cuda:0')

In [205]:
# Looking for the max value of the result
result_of_multiplying.max()

torch.device

In [211]:
# Looking for the min value of the result
result_of_multiplying.min()

tensor(0.5279, device='cuda:0')

In [212]:
# Looking for the mean of the result
result_of_multiplying.mean()

tensor(0.7550, device='cuda:0')

In [213]:
# Looking for the index of the max value
result_of_multiplying.argmax()

tensor(2, device='cuda:0')

In [215]:
# Looking for the index of the min value
result_of_multiplying.argmin()

tensor(3, device='cuda:0')

#### Making a radnom tensor of shape `(1, 1, 1, 10)` and then creating a new tensor with all the `1` dimensions removed

In [216]:
random_tensor = torch.rand(1, 1, 1, 10)
random_tensor

tensor([[[[0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298, 0.7231,
           0.7423, 0.5263]]]])

In [218]:
squeezed_random_tensor = random_tensor.squeeze()
squeezed_random_tensor

tensor([0.9320, 0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298, 0.7231, 0.7423,
        0.5263])

In [219]:
torch.manual_seed(7)

In [220]:
print(f"Shape of the old tensor: {random_tensor.shape}")
print(f"Shape of the new tensor: {squeezed_random_tensor.shape}")

Shape of the old tensor: torch.Size([1, 1, 1, 10])
Shape of the new tensor: torch.Size([10])
