<a href="https://colab.research.google.com/github/emagif/PyTorch/blob/main/00_PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


### Introduction to Tensors

#### Creating Tensors

#### Pytorch tensors are created using torch.Tensor()

# Scalar

In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

# Matrix

In [8]:
MATRIX = torch.tensor([[7, 8], [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX[1]

tensor([ 9, 10])

# Tensor


In [13]:
TENSOR = torch.tensor([[[1, 2, 3], [3, 6, 7], [2, 1, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 7],
         [2, 1, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 7],
        [2, 1, 5]])

In [17]:
tensor1 = torch.tensor([[[1, 2, 3, 4, 5], [4, 5, 6, 7, 8], [9, 0, 2, 3, 4]]])
tensor1

tensor([[[1, 2, 3, 4, 5],
         [4, 5, 6, 7, 8],
         [9, 0, 2, 3, 4]]])

In [18]:
tensor1.shape

torch.Size([1, 3, 5])

In [19]:
tensor1.ndim

3

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full or random numbers and thej adjust those random numbers to better represent the data.

'Start with random numbers -> look at data -> update random numbers -> look at data -> update'

In [20]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9159, 0.5773, 0.5334, 0.4020],
        [0.4888, 0.3442, 0.1258, 0.3985],
        [0.5684, 0.0426, 0.3980, 0.8078]])

In [21]:
random_tensor.ndim

2

In [22]:
random_image_tensor = torch.rand(size=(224, 224, 3))
random_image_tensor

tensor([[[0.7168, 0.4178, 0.4863],
         [0.2496, 0.8125, 0.2810],
         [0.8701, 0.0276, 0.2947],
         ...,
         [0.7884, 0.9666, 0.6575],
         [0.2599, 0.5248, 0.8329],
         [0.1367, 0.4082, 0.6223]],

        [[0.7880, 0.4667, 0.1089],
         [0.8849, 0.9303, 0.7309],
         [0.4484, 0.2811, 0.5513],
         ...,
         [0.2802, 0.4437, 0.5740],
         [0.1859, 0.0627, 0.9810],
         [0.5870, 0.4278, 0.8194]],

        [[0.8840, 0.5089, 0.4414],
         [0.5202, 0.7887, 0.8284],
         [0.2059, 0.4531, 0.2443],
         ...,
         [0.1078, 0.5198, 0.9326],
         [0.1561, 0.6592, 0.5591],
         [0.2375, 0.2868, 0.3388]],

        ...,

        [[0.2836, 0.1509, 0.4041],
         [0.3069, 0.1032, 0.5894],
         [0.5182, 0.7279, 0.8723],
         ...,
         [0.5670, 0.6664, 0.7820],
         [0.1251, 0.9671, 0.3091],
         [0.4162, 0.0567, 0.3507]],

        [[0.8956, 0.1733, 0.9116],
         [0.4521, 0.6772, 0.3659],
         [0.

In [23]:
random_image_tensor.ndim

3

In [24]:
random_image_tensor.shape


torch.Size([224, 224, 3])

## Zeros and ones

In [25]:
zero = torch.zeros(3, 4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zero*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

In [29]:
random_tensor.dtype

torch.float32

# Create a range od tensor and tensors-like

In [30]:
one_to_ten = torch.arange(0, 10)

## Creating tensors-like

In [31]:
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)
float_32_tensor

tensor([3., 6., 9.])

## Tensor atributes

In [36]:
int_32_tensor = torch.tensor([3, 6, 9], dtype = torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [37]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors

1. Tensors not right datatype - to do get datatype from a tensor,can use 'tensor.dtype'
2. Tensors not right shape - to get shape from tensor, can use 'tensor.shape'
3. Tensors not on the right device - to get device from a tensor, can use 'tensor.device'


In [39]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2617, 0.0665, 0.0802, 0.3043],
        [0.5339, 0.1305, 0.3646, 0.5438],
        [0.2182, 0.3884, 0.1113, 0.9738]])

In [40]:
print(f"Shape of tensor: {some_tensor.shape}")

Shape of tensor: torch.Size([3, 4])


In [41]:
print(f"Datatype of tensor: {some_tensor.dtype}")

Datatype of tensor: torch.float32


In [42]:
print(f"Device tensor is on: {some_tensor.device}")

Device tensor is on: cpu


2h 11min